In [2]:
# 1. Импорт библиотеки NumPy с общепринятым сокращением.
import numpy as np

In [3]:
# 2. Примеры создания массивов:

# Из обычного списка
python_list = [1, 2, 3, 4, 5]
array_from_list = np.array(python_list)
print("Массив из списка:", array_from_list)

# Использование zeros - массив нулей
zeros_array = np.zeros((2, 3))
print("Массив нулей 2x3:")
print(zeros_array)

# Использование ones - массив единиц
ones_array = np.ones((3, 2))
print("Массив единиц 3x2:")
print(ones_array)

# Использование arange - последовательность чисел
range_array = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
print("Массив от 0 до 10 с шагом 2:", range_array)


Массив из списка: [1 2 3 4 5]
Массив нулей 2x3:
[[0. 0. 0.]
 [0. 0. 0.]]
Массив единиц 3x2:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Массив от 0 до 10 с шагом 2: [0 2 4 6 8]


In [5]:
# 3. Демонстрация атрибутов:
print("Демонстрационный массив:")
print(zeros_array)

# Вывод формы массива (shape)
print("Форма массива (shape):", zeros_array.shape)

# Вывод типа данных (dtype)
print("Тип данных (dtype):", zeros_array.dtype)


Демонстрационный массив:
[[0. 0. 0.]
 [0. 0. 0.]]
Форма массива (shape): (2, 3)
Тип данных (dtype): float64


In [6]:
# 4. Примеры индексирования и срезов:
# Создаем массив для работы с индексами
arr = np.array([[10, 11, 12, 13],
                [20, 21, 22, 23],
                [30, 31, 32, 33]])

print("Исходный массив:")
print(arr)

# Получение отдельного элемента
element = arr[1, 2]  # строка 1, столбец 2
print("Элемент [1, 2]:", element)

# Извлечение подмассива с помощью среза
sub_array = arr[0:2, 1:3]  # строки 0-1, столбцы 1-2
print("Подмассив [0:2, 1:3]:")
print(sub_array)

# Другие примеры срезов
first_row = arr[0, :]  # первая строка, все столбцы
print("Первая строка:", first_row)

every_second_row = arr[::2, :]  # каждая вторая строка
print("Каждая вторая строка:")
print(every_second_row)

Исходный массив:
[[10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]
Элемент [1, 2]: 22
Подмассив [0:2, 1:3]:
[[11 12]
 [21 22]]
Первая строка: [10 11 12 13]
Каждая вторая строка:
[[10 11 12 13]
 [30 31 32 33]]


In [9]:
# 5. Примеры векторных операций и базовых статистик:
# Создаем массивы для операций
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4, 6, 8, 10])

print("Массив A:", a)
print("Массив B:", b)

# Поэлементное сложение
addition = a + b
print("Поэлементное сложение A + B:", addition)

# Поэлементное умножение
multiplication = a * b
print("Поэлементное умножение A * B:", multiplication)

# Вычисление статистик для массива A
print("\nСтатистики для массива A:")
print("Среднее значение (mean):", np.mean(a))
print("Сумма элементов (sum):", np.sum(a))
print("Минимальное значение (min):", np.min(a))


Массив A: [1 2 3 4 5]
Массив B: [ 2  4  6  8 10]
Поэлементное сложение A + B: [ 3  6  9 12 15]
Поэлементное умножение A * B: [ 2  8 18 32 50]

Статистики для массива A:
Среднее значение (mean): 3.0
Сумма элементов (sum): 15
Минимальное значение (min): 1
